language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - echo "Build Process started"
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed #Build the images
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed charliecool023/udagram-api-feed:v1
  - docker tag udagram-api-user charliecool023/udagram-api-user:v2
  - docker tag udagram-frontend charliecool023/udagram-frontend:v4
  - docker tag udagram-reverseproxy charliecool023/reverseproxy:v3
  - echo "Build Process completed successfully"
# Tasks to perform after the process is successful.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push charliecool023/udagram-api-feed:v1
  - docker push charliecool023/udagram-api-user:v2
  - docker push charliecool023/udagram-frontend:v4
  - docker push charliecool023/reverseproxy:v3
  - echo "push success"
