apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
        - name: backend-user
          image: sade1/udagram-api-user:v1
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          env:
            - name: POSTGRES_USERNAME
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "protected"
            - name: POSTGRES_HOST
              value: "webchi.c45vpqc5llaf.us-east-1.rds.amazonaws.com"
            - name: POSTGRES_DB
              value: "postgres"